//
//  CI.swift
//  
//
//  Created by Yerzhan Utkelbayev on 18/08/2025.
//

name: iOS CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_16.3.app"
      - name: SwiftFormat & SwiftLint
        run: |
          brew install swiftformat swiftlint || true
          swiftformat . --lint
          swiftlint --strict
      - name: Build
        run: |
          xcodebuild -workspace PushupPro.xcworkspace \
            -scheme PushupProApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' \
            clean build
